ARG REGISTRY=docker.io/library

FROM ${REGISTRY}/mm_agimus:control

user gepetto

# clone dev-config
RUN cd; git clone https://github.com/xmatousm/agimus-dev-config.git

RUN mkdir -p ~/ros2_ws
RUN ln -s ~/agimus-dev-config/run ~/run
RUN ln -s ~/agimus-dev-config/run ~/ros2_ws/run

# download/install dependencies
RUN ~/run get

# buld workspace
RUN ~/run build
