ARG REGISTRY=gitlab.laas.fr:4567

FROM ${REGISTRY}/agimus-project/agimus_dev_container:humble-devel-control-2025

USER root

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
         xauth \
         xterm \
         mc \
         less \
         openssh-server \
         ros-${ROS_DISTRO}-rqt-controller-manager \
         ros-${ROS_DISTRO}-plotjuggler \
         ros-${ROS_DISTRO}-plotjuggler-ros \
    && rm -rf /var/lib/apt/lists/*

USER gepetto

# install some dependencies
RUN --mount=type=bind,target=/build,source=./ /build/run deps && sudo rm -rf /var/lib/apt/lists/*

RUN chmod a+rX /home/gepetto
RUN chmod -R a+rX /home/gepetto/ros2_ws/
