ARG REGISTRY=gitlab.laas.fr:4567

FROM ${REGISTRY}/agimus-project/agimus_dev_container:humble-devel-control-2025

USER root

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
         xauth \
         xterm \
         mc \
         less \
         openssh-server \
         ros-${ROS_DISTRO}-rqt-controller-manager \
         ros-${ROS_DISTRO}-plotjuggler \
         ros-${ROS_DISTRO}-plotjuggler-ros \
    && rm -rf /var/lib/apt/lists/*

USER gepetto

COPY . /home/gepetto/agimus-dev-config
RUN cd; ls
RUN ln -s ~/agimus-dev-config/run ~/run

# install some dependencies
RUN ~/run deps && sudo rm -rf /var/lib/apt/lists/*

RUN ln -s ~/agimus-dev-config/run ~/ros2_ws/run

RUN chmod a+rX /home/gepetto
RUN chmod -R a+rX /home/gepetto/ros2_ws/
