ARG REGISTRY=docker.io/library

FROM ${REGISTRY}/mm_agimus:control

RUN cd; rm -rf agimus-dev-config
RUN cd; git clone https://github.com/xmatousm/agimus-dev-config.git
RUN ln -s -f ~/agimus-dev-config/run ~/run

# download/install dependencies
RUN ~/run get

# buld workspace
RUN ~/run build

RUN ln -s -f ~/agimus-dev-config/run ~/ros2_ws/run
