ARG REGISTRY=docker.io/library

FROM ${REGISTRY}/mm_agimus:control

RUN cd; git clone https://github.com/xmatousm/agimus-dev-config.git
RUN cd; ls
RUN ln -s ~/agimus-dev-config/run ~/run

# download/install dependencies
RUN ~/run get

# buld workspace
RUN ~/run build
