#!/bin/bash
# Helper script to run various tasks

# The directory of this script
SCRIPT="$(readlink -f "$0")"
BASE="$(dirname "$SCRIPT")"

# The workspace
WS="$HOME/ros2_ws"
mkdir -p "$WS"
cd "$WS" || exit 255

# options, default and commandline
export ROS_LOCALHOST_ONLY=0

cmd=""
OPTS=(tool_id:=knife)
HW=0
RID=kuka  # robot class (franka, kuka)
RSUFF="_kuka"
RNAME="lbr"  # robot name used as ROS namespace
#OPTS+=(robot_name:=capek2)

CMDS0=(-rviz -gz-headless -use-aux -hw "-f[ranka]" "-k[uka]")
for arg in "${@}"; do
    case "$arg" in
        -rviz)
            OPTS+=("use_rviz:=true")
            ;;

        -gz-headless)
            OPTS+=("gz_headless:=true")
            ;;

        -use-aux)
            OPTS+=("use_aux:=true")
            ;;

        -on-aux)
            OPTS+=("on_aux:=true")
            ;;

        -hw)
            HW=1
            ;;

        -debug-lfc)
            OPTS+=("use_passthrough_state_publisher:=true"
                   "linear_feedback_controller_params:=${RNAME}_linear_feedback_controller_params_debug.yaml")
            ;;

        -franka|-f|-panda|-p)
            RID=franka
            RSUFF=""
            ;;

        -kuka|-k)
            RID=kuka
            RSUFF=_kuka
            ;;

        *)
            if [ -z "$cmd" ]; then
                cmd="$arg"
            else
                echo "Unhandled multiple cmdline arguments; next is $arg"
                exit 255
            fi
            ;;
    esac
done

OPTS+=("use_mpc_debugger:=markers")

# hardware or simulation
if [ "$HW" == "0" ]; then
    OPTS+=("use_gazebo:=true")
fi


# init and build utilities
CMDS1=(get build)

case "$cmd" in
    get)
        bash "$BASE/ws_get.sh"
        exit
        ;;

    build)
        bash "$BASE/ws_build.sh"
        exit
        ;;
esac

source ~/ros2_ws/install/setup.bash


# some tools
CMDS2=(kill plot dev devs devc devcs pylon)

case "$cmd" in
    kill)
       killall -9 ruby
       killall -9 /usr/bin/python3
       killall -9 /opt/ros/humble/lib/robot_state_publisher/robot_state_publisher
       killall -9 /opt/ros/humble/lib/tf2_ros/static_transform_publisher
       killall -9 /opt/ros/humble/lib/ros_gz_sim/create

       exit
       ;;

    plot)
        ros2 run plotjuggler plotjuggler
        exit
        ;;

    dev)
        /usr/local/PyCharm/bin/pycharm
        exit
        ;;

    devs)
        /usr/local/PyCharm/bin/remote-dev-server run
        exit
        ;;

    devc)
        /usr/local/CLion/bin/clion
        exit
        ;;

    devcs)
        /usr/local/CLion/bin/remote-dev-server run
        exit
        ;;

    pylon)
        /opt/pylon/bin/pylonviewer
        exit
        ;;
esac


# ros launchers for tasks
CMDS3=(aux rviz "home[012]" zero 0 1 2 3 3a 3o 3l 3c 13 13j 14 15)

LAUNCH=bringup.launch.py
case "$cmd" in
    aux)
        PKG=agimus_demos_common
        LAUCH=${RID}_common_lfc.launch.py
        OPTS+=(on_aux:=true)
        ;;

    rviz)
        PKG=agimus_demos_common
        LAUNCH=${RID}_rviz.launch.py
        ;;

    home0 | home1 | home2 | home3 | zero)
        PKG=agimus_demo_00_${RID}_controller
        OPTS+=(preset:=${cmd})
        ;;

    0)
        PKG=agimus_demo_00_${RID}_controller
        ;;

    1)
        PKG=agimus_demo_01_lfc_alone${RSUFF}
        ;;

    2)
        PKG=agimus_demo_02_simple_pd_plus${RSUFF}
        ;;

    3)
        PKG=agimus_demo_03_mpc_dummy_traj${RSUFF}
        ;;

    3f)
        PKG=agimus_demo_03a_mpc_full_dummy_traj${RSUFF}
        ;;

    3fa)
        PKG=agimus_demo_03a_mpc_full_dummy_traj${RSUFF}
        OPTS+=(trajectory_config_file:=trajectory_weigths_params_adaptive.yaml)
        ;;

    3o)
        PKG=agimus_demo_03_mpc_dummy_traj${RSUFF}
        OPTS+=(mod_publisher:=true \
               trajectory_config_file:=trajectory_weigths_params_line_obstacle.yaml \
               obstacles_config_file:=obstacles.xacro \
               ocp_definition_file:=ocp_definition_file_obstacle.yaml)
        ;;

    3l)
        PKG=agimus_demo_03_mpc_dummy_traj${RSUFF}
        OPTS+=(mod_publisher:=true \
               trajectory_config_file:=trajectory_weigths_params_line.yaml \
               controller_config_file:=agimus_controller_params_line.yaml)
        ;;

    3s)
        PKG=agimus_demo_03_mpc_dummy_traj${RSUFF}
        OPTS+=(mod_publisher:=true \
               trajectory_config_file:=trajectory_weigths_params_saw.yaml \
               controller_config_file:=agimus_controller_params_line.yaml)
        ;;


    3c)
        PKG=agimus_demo_03_mpc_dummy_traj${RSUFF}
        OPTS+=(mod_publisher:=true \
               trajectory_config_file:=trajectory_weigths_params_calib.yaml \
               controller_config_file:=agimus_controller_params_line.yaml)
        ;;


    13)
        PKG=agimus_demo_13_mpc_dummy_goal${RSUFF}
        ;;

    13s)
        PKG=agimus_demo_13_mpc_dummy_goal${RSUFF}
        OPTS+=(trajectory_config_file:=trajectory_weigths_params_saw.yaml)
        ;;

    14)
        PKG=agimus_demo_14_cardboard_detect
        OPTS+=(camera_embedded:=true)
        OPTS+=(template:=agimus_cardboard:templates/template_1.yml)
        if [ "$HW" == "0" ]; then
            OPTS+=(simulate:=agimus_demo_14_cardboard_detect:config/image_1.png)
        fi
        ;;

    15)
        PKG=agimus_demo_15_cardboard
        OPTS+=(camera_embedded:=true)
        OPTS+=(template:=agimus_cardboard:templates/template_1.yml)
        ;;


    *)
        echo "Unknown command $cmd; known optons:"
        echo "  " ${CMDS0[@]}
        echo "  and commands:"
        echo "  " ${CMDS1[@]}
        echo "  " ${CMDS2[@]}
        echo "  " ${CMDS3[@]}
        exit
        ;;
esac

# run the task
echo Running: ros2 launch "${PKG}" "${LAUNCH}" "${OPTS[@]}"
ros2 launch "${PKG}" "${LAUNCH}" "${OPTS[@]}"

