#!/bin/bash
# Helper script to run various tasks

# The directory of this script
SCRIPT="$(readlink -f "$0")"
BASE="$(dirname "$SCRIPT")"

# The workspace
WS="$HOME/ros2_ws"
mkdir -p "$WS"
cd "$WS" || exit 255

# options, default and commandline
export ROS_LOCALHOST_ONLY=0
OPTS=()
LAUNCH_OPTS=()
cmd=""

TOOL=knife
OPTS+=("use_mpc_debugger:=markers")
HW=0
RID=kuka  # robot class (franka, kuka)
RSUFF="_kuka"
RNAME="lbr"  # robot name used as ROS namespace
WSUFF=""  # workplace setup suffix

HELP_OPTIONS='
    -rviz -gz-headless -use-aux -on-aux -hw -f[ranka] -k[uka]
    -1 -2  ... selects particular workplace (suffix and tool)
    -d     ... debug mode of launch files'

# parse options
for arg in "${@}"; do
    case "$arg" in
        -rviz)
            OPTS+=("use_rviz:=true")
            ;;

        -gz-headless)
            OPTS+=("gz_headless:=true")
            ;;

        -use-aux)
            OPTS+=("use_aux:=true")
            ;;

        -on-aux)
            OPTS+=("on_aux:=true")
            ;;

        -hw)
            HW=1
            ;;

        -1)
            WSUFF="_1"
            TOOL=gripper
            ;;

        -2)
            WSUFF="_2"
            TOOL=knife
            ;;

        -debug-lfc)
            OPTS+=("use_passthrough_state_publisher:=true"
                   "linear_feedback_controller_params:=${RNAME}_linear_feedback_controller_params_debug.yaml")
            ;;

        -franka|-f|-panda|-p)
            RID=franka
            RSUFF=""
            ;;

        -kuka|-k)
            RID=kuka
            RSUFF=_kuka
            ;;

        -d)
            LAUNCH_OPTS+=("-d")
            ;;

        *)
            if [ -z "$cmd" ]; then
                cmd="$arg"
            else
                echo "Unhandled multiple cmdline arguments; next is $arg"
                exit 255
            fi
            ;;
    esac
done

# apply options
OPTS+=("robot_name:=$RNAME")
OPTS+=("system_config_path:=agimus_demos_common_kuka:config/kuka/${RNAME}_system_config${WSUFF}.yaml")

if [ "$HW" == "0" ]; then
    OPTS+=("use_gazebo:=true")
fi

# init and build utilities
CMDS1=(deps get build)

case "$cmd" in
    deps)
        bash "$BASE/ws_deps.sh"
        exit
        ;;

    get)
        bash "$BASE/ws_get.sh"
        exit
        ;;

    build)
        bash "$BASE/ws_build.sh"
        exit
        ;;
esac

# shellcheck disable=SC1090
source ~/ros2_ws/install/setup.bash

# some tools
CMDS2=(kill plot dev devs devc devcs pylon)

case "$cmd" in
    kill)
       killall -9 ruby
       killall -9 /usr/bin/python3
       killall -9 /opt/ros/humble/lib/robot_state_publisher/robot_state_publisher
       killall -9 /opt/ros/humble/lib/tf2_ros/static_transform_publisher
       killall -9 /opt/ros/humble/lib/ros_gz_sim/create
       exit
       ;;

    plot)
        ros2 run plotjuggler plotjuggler
        exit
        ;;

    dev)
        /usr/local/PyCharm/bin/pycharm
        exit
        ;;

    devs)
        /usr/local/PyCharm/bin/remote-dev-server run
        exit
        ;;

    devc)
        /usr/local/CLion/bin/clion
        exit
        ;;

    devcs)
        /usr/local/CLion/bin/remote-dev-server run
        exit
        ;;

    pylon)
        /opt/pylon/bin/pylonviewer
        exit
        ;;
esac


# ros launchers for tasks
CMDS3=(aux rviz "home[0123]" zero 0 1 2 3 3f 3fa 3o 3l 3s 3c 13 13s 13g 14 15 16)

LAUNCH=bringup.launch.py

case "$cmd" in
    aux)
        PKG=agimus_demos_common_kuka
        LAUNCH=${RID}_common_lfc.launch.py
        OPTS+=(on_aux:=true)
        ;;

    rviz)
        PKG=agimus_demos_common_kuka
        LAUNCH=${RID}_rviz.launch.py
        ;;

    home0 | home1 | home2 | home3 | zero)
        PKG=agimus_demo_00_${RID}_controller
        OPTS+=(preset:=${cmd})
        ;;

    0)
        PKG=agimus_demo_00_${RID}_controller
        TOOL=
        ;;

    1)
        PKG=agimus_demo_01_lfc_alone${RSUFF}
        TOOL=
        ;;

    2)
        PKG=agimus_demo_02_simple_pd_plus${RSUFF}
        TOOL=
        ;;

    3)
        PKG=agimus_demo_03_mpc_dummy_traj${RSUFF}
        ;;

    3f)
        PKG=agimus_demo_03a_mpc_full_dummy_traj${RSUFF}
        ;;

    3fa)
        PKG=agimus_demo_03a_mpc_full_dummy_traj${RSUFF}
        OPTS+=(trajectory_config_file:=trajectory_weigths_params_adaptive.yaml)
        ;;

    3o)
        PKG=agimus_demo_03_mpc_dummy_traj${RSUFF}
        OPTS+=(mod_publisher:=true \
               trajectory_config_file:=trajectory_weigths_params_line_obstacle.yaml \
               obstacles_config_file:=obstacles.xacro \
               ocp_definition_file:=ocp_definition_file_obstacle.yaml)
        ;;

    3l)
        PKG=agimus_demo_03_mpc_dummy_traj${RSUFF}
        OPTS+=(mod_publisher:=true \
               trajectory_config_file:=trajectory_weigths_params_line.yaml \
               controller_config_file:=agimus_controller_params_line.yaml)
        ;;

    3s)
        PKG=agimus_demo_03_mpc_dummy_traj${RSUFF}
        OPTS+=(mod_publisher:=true \
               trajectory_config_file:=trajectory_weigths_params_saw.yaml \
               controller_config_file:=agimus_controller_params_line.yaml)
        ;;


    3c)
        PKG=agimus_demo_03_mpc_dummy_traj${RSUFF}
        OPTS+=(mod_publisher:=true \
               trajectory_config_file:=trajectory_weigths_params_calib.yaml \
               controller_config_file:=agimus_controller_params_line.yaml)
        ;;


    13)
        PKG=agimus_demo_13_mpc_dummy_goal${RSUFF}
        ;;

    13s)
        PKG=agimus_demo_13_mpc_dummy_goal${RSUFF}
        OPTS+=(trajectory_config_file:=trajectory_weigths_params_saw.yaml)
        ;;

    13g)
        PKG=agimus_demo_13_mpc_dummy_goal${RSUFF}
        OPTS+=(trajectory_config_file:=trajectory_weigths_params_gripper.yaml)
        OPTS+=(gripper_eth:=192.168.100.31)
        ;;

    14)
        PKG=agimus_demo_14_cardboard_detect${RSUFF}
        OPTS+=(camera_embedded:=true)

        #OPTS+=(template:=agimus_cardboard:templates/template_1.yml)
        OPTS+=(template:=agimus_cardboard:templates/template_B_1.yml)

        OPTS+=(detector:=agimus_demos_common_kuka:config/kuka/detector${WSUFF}.yaml)
        OPTS+=(calib_cam:=agimus_demos_common_kuka:config/kuka/calib_cam${WSUFF}.yaml)
        OPTS+=(calib_robot:=agimus_demos_common_kuka:config/kuka/calib_robot${WSUFF}.yaml)

        OPTS+=(mask:=agimus_demos_common_kuka:config/kuka/mask${WSUFF}.png)

        if [ "$HW" == "0" ]; then
            OPTS+=(simulate:=agimus_demos_common_kuka:config/kuka/image${WSUFF}.png)
        fi
        ;;

    15)
        PKG=agimus_demo_15_cardboard${RSUFF}
        OPTS+=(camera_embedded:=true)

        #OPTS+=(template:=agimus_cardboard:templates/template_1.yml)
        OPTS+=(template:=agimus_cardboard:templates/template_B_1.yml)

        OPTS+=(detector:=agimus_demos_common_kuka:config/kuka/detector${WSUFF}.yaml)
        OPTS+=(calib_cam:=agimus_demos_common_kuka:config/kuka/calib_cam${WSUFF}.yaml)
        OPTS+=(calib_robot:=agimus_demos_common_kuka:config/kuka/calib_robot${WSUFF}.yaml)

        OPTS+=(mask:=agimus_demos_common_kuka:config/kuka/mask${WSUFF}.png)

        if [ "$HW" == "0" ]; then
            OPTS+=(simulate:=agimus_demos_common_kuka:config/kuka/image${WSUFF}.png)
        fi
       ;;

    16)
        PKG=agimus_demo_16_cardboard_insert${RSUFF}
        OPTS+=(camera_embedded:=true)

        OPTS+=(template:=agimus_cardboard:templates/template_B_1.yml)

        OPTS+=(detector:=agimus_demos_common_kuka:config/kuka/detector${WSUFF}.yaml)
        OPTS+=(calib_cam:=agimus_demos_common_kuka:config/kuka/calib_cam${WSUFF}.yaml)
        OPTS+=(calib_robot:=agimus_demos_common_kuka:config/kuka/calib_robot${WSUFF}.yaml)

        if [ "$HW" == "0" ]; then
            OPTS+=(simulate:=agimus_demos_common_kuka:config/kuka/image${WSUFF}.png)
        fi
        ;;


    *)
        echo "Unknown command $cmd; known optons:$HELP_OPTIONS"
        echo "  and commands:"
        echo "    ${CMDS1[*]}"
        echo "    ${CMDS2[*]}"
        echo "    ${CMDS3[*]}"
        exit
        ;;
esac

if [ -n "$TOOL" ]; then
  OPTS+=("tool_id:=$TOOL")
fi

# run the task
echo Running: ros2 launch "${LAUNCH_OPTS[@]}" "${PKG}" "${LAUNCH}" "${OPTS[@]}"
ros2 launch "${LAUNCH_OPTS[@]}" "${PKG}" "${LAUNCH}" "${OPTS[@]}"
